workflows:
  kivy_build:
    name: Build Kivy APK
    environment:
      groups:
        - default   # Ye tumhara HUGGINGFACE_API_KEY env var load karega
    scripts:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install buildozer
      - buildozer init || true
      - buildozer -v android debug
    artifacts:
      - build/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com   # Yahan apna email likho jahan APK ka link aayega
