workflows:
  kivy_build:
    name: Build Kivy APK
    environment:
      vars:
        PYTHON_VERSION: "3.9"
    scripts:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install buildozer
      - buildozer init || true
      - buildozer -v android debug
    artifacts:
      - build/*.apk
